{% set version = '0.1.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mwcsr
  version: {{ version|replace("-", "_") }}

source:
  url:     {{ cran_mirror }}/src/contrib/Archive/mwcsr/mwcsr_{{ version }}.tar.gz
  sha256: 170d312ec68905c86e760551d7a35db8bce8246ace6a2ec5405530040eefdb6f

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - r-igraph                     # [build_platform != target_platform]
    - r-rcpp                       # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib('c') }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib('m2w64_c') }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-igraph
    - r-rcpp
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-igraph
    - r-rcpp

test:
  commands:
    - $R -e "library('mwcsr')"           # [not win]
    - "\"%R%\" -e \"library('mwcsr')\""  # [win]

about:
  home: https://github.com/ctlab/mwcsr
  license: MIT
  summary: "Algorithms for solving various Maximum Weight Connected Subgraph Problems, including
    variants with budget constraints, cardinality constraints, weighted edges and signals.
    The package represents an R interface to high-efficient solvers based on relax-and-cut
    approach (\xC1lvarez-Miranda E., Sinnl M. (2017) <doi:10.1016/j.cor.2017.05.015>)
    mixed-integer programming (Loboda A., Artyomov M., and Sergushichev A. (2016) <doi:10.1007/978-3-319-43681-4_17>)
    and simulated annealing."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: mwcsr
# Title: Solvers for Maximum Weight Connected Subgraph Problem and Its Variants
# Version: 0.1.8
# Authors@R: c(person("Alexander", "Loboda", email = "aleks.loboda@gmail.com", role = c("aut", "cre")), person("Nikolay", "Poperechnyi", email = "n.poperechnyi@gmail.com", role = "aut"), person("Eduardo", "Alvarez-Miranda", email = "ealvarez@utalca.cl", role = "aut"), person("Markus", "Sinnl", email = "markus.sinnl@univie.ac.at", role = "aut"), person("Alexey", "Sergushichev", email = "alsergbox@gmail.com", role = "aut"), person("Paul", "Hosler Jr.", role = "cph", comment = "Bundled JOpt Simple package"), person("www.hamcrest.org", role = "cph", comment = "Bundled hamcrest package"), person("Barak Naveh and Contributors", role = "cph", comment = "Bundled JGraphT package"), person("The Apache Software Foundation", role = "cph", comment = "Bundled Apache Commons Math package"))
# Description: Algorithms for solving various Maximum Weight Connected Subgraph Problems, including variants with budget constraints, cardinality constraints, weighted edges and signals. The package represents an R interface to high-efficient solvers based on relax-and-cut approach (Alvarez-Miranda E., Sinnl M. (2017) <doi:10.1016/j.cor.2017.05.015>) mixed-integer programming (Loboda A., Artyomov M., and Sergushichev A. (2016) <doi:10.1007/978-3-319-43681-4_17>) and simulated annealing.
# Depends: R (>= 3.5)
# Imports: methods, igraph, Rcpp
# Suggests: knitr, rmarkdown, mathjaxr, testthat, BioNet, roxygen2, DLBCL
# SystemRequirements: Java (>=8)
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 7.2.2
# VignetteBuilder: knitr
# URL: https://github.com/ctlab/mwcsr
# BugReports: https://github.com/ctlab/mwcsr/issues
# LinkingTo: Rcpp
# NeedsCompilation: yes
# Packaged: 2024-03-02 09:20:48 UTC; aloboda
# Author: Alexander Loboda [aut, cre], Nikolay Poperechnyi [aut], Eduardo Alvarez-Miranda [aut], Markus Sinnl [aut], Alexey Sergushichev [aut], Paul Hosler Jr. [cph] (Bundled JOpt Simple package), www.hamcrest.org [cph] (Bundled hamcrest package), Barak Naveh and Contributors [cph] (Bundled JGraphT package), The Apache Software Foundation [cph] (Bundled Apache Commons Math package)
# Maintainer: Alexander Loboda <aleks.loboda@gmail.com>
# Repository: CRAN
# Date/Publication: 2024-03-02 10:40:02 UTC
